version: '3.8'

services:
  mysql:
    image: mysql:8.0.38
    container_name: buma-view-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bumaView
    ports:
      - "3306:3306"